# Docker Compose para Kafka e Zookeeper - Ambiente de Desenvolvimento
version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.3
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.5.3
    container_name: kafka
    hostname: kafka
    depends_on:
      - zookeeper
    ports:
      # Porta para acesso externo (da sua máquina host para o container)
      - "29092:29092"
      # Porta para comunicação interna na rede Docker (ex: entre brokers)
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      # Configura os listeners para o Kafka: um para a rede interna e outro para a externa.
      # PLAINTEXT://kafka:9092 -> Para outros containers se conectarem
      # PLAINTEXT_HOST://localhost:29092 -> Para sua aplicação (host) se conectar
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

networks:
  default:
    name: kafka-network